kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ikaruswill/octopi-wp-web
    tags:
      - latest
      - ${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag
